# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: poetry-lock
        name: Poetry Lock
        entry: bash -c 'command -v poetry && poetry lock --no-update && git add poetry.lock || echo "Poetry not found"'
        language: system
        pass_filenames: false
        files: ^pyproject\.toml$

      - id: poetry-install
        name: Poetry Install
        entry: bash -c 'command -v poetry && poetry install || echo "Poetry not found"'
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--ignore=E203,E231,E226"]
